### ISSUE TITLE
What is the meaning of the dataset?

### ISSUE THREAD

**Issue by yiping-wang** [arneish/parallel-k-means#1]
I am pretty curious what's the meaning or source of the dataset. Is it just randomly generated?

Thanks for replying!

**Comment by arneish** [comment]
Hi, you could check the dataset generating file in the repo [link](https://github.com/arneish/parallel-k-means/blob/master/dataset.py). It is not exactly random.

**Comment by arneish** [comment]
Hi, you could check the dataset generating file in the repo named [dataset.py](https://github.com/arneish/parallel-k-means/blob/master/dataset.py). It is not exactly a random data generator, it follows some distribution.
